### ISSUE TITLE
Security Updates

### ISSUE THREAD

**Issue by SupposedlySam** [mateendev3/lets_chat#2]
Hey Mateen,

I'm sure you have plans to remedy this situation, but right now you have a few issues I wanted to make you aware of if you weren't already.

Since this is an open source project, deleting files is not enough to stop someone from getting any data that was committed previously. For instance, when you ["Added Firebase to app"](https://github.com/mateendev3/lets_chat/commit/6a696af97692b5613b40b80a843c6352e6ee0d12) you leaked all of your credentials you later tried to remove. This actually isn't bad in of itself. These keys are unique, but not private. However, you need to ensure you write the [appropriate security rules](https://firebase.google.com/docs/rules/basics) for your database so someone can't come in and wreak havoc.

Personally, without even being authorized, I was able to list all of your `users` information (only test data right now from what I can tell -- other than maybe your real phone number), create my own user, and edit my profile pic. Check your database and you'll see my user ;)

```json
{
  "fields": {
    "uid": {
      "stringValue": "530fdkrE4ROD81qC93ny1UIgC489"
    },
    "name": {
      "stringValue": "SupposedlySamWasHere"
    },
    "phoneNumber": {
      "stringValue": "+19058675309"
    },
    "groupId": {
      "arrayValue": {}
    },
    "profilePic": {
      "stringValue": "https://media.istockphoto.com/vectors/profile-picture-vector-illustration-vector-id587805156?k=20&m=587805156&s=612x612&w=0&h=Ok_jDFC5J1NgH20plEgbQZ46XheiAF8sVUKPvocne6Y="
    },
    "isOnline": {
      "booleanValue": true
    }
  },
  "createTime": "2022-10-14T16:31:31.723462Z",
  "updateTime": "2022-10-14T16:55:51.412283Z"
}
```

Note: feel free to delete this user as I was only using it to test your database rules.

Just wanted to let you know this is possible! I used the Firestore REST api to make the requests.

Open to a conversation here if you need more info.

Here are some resources that I found helpful when learning about Firestore rules:
- [Security Rules! 🔑 | Get to know Cloud Firestore #6](https://youtu.be/eW5MdE3ZcAw)
- [Security Rules deep dive | Better Safe than Sorry](https://youtu.be/TglPc74M3DM)
- [Introduction to Firebase Security Rules - Firecasts](https://www.youtube.com/watch?v=QEuu9X9L-MU&list=PLl-K7zZEsYLn8h1NyU_OV6dX8mBhH2s_L)

**Comment by mateendev3** [comment]
Thanks for the help man.
Gonna learn firestore rules.

**Comment by SupposedlySam** [comment]
I believe this is still an issue.

https://firestore.googleapis.com/v1/projects/lets-chat-mateendev3/databases/(default)/documents/users
